# Generated by Django 2.2.7 on 2019-11-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProductos', '0002_auto_20191128_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_Padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre de categoria', max_length=50, verbose_name='Nombre de categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='categoria_padre',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoriaPadre', to='AppProductos.Categoria_Padre'),
        ),
    ]
