# Generated by Django 2.2.7 on 2019-11-28 19:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParteInforme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('sa', 'SANTIARIA'), ('fu', 'FUNCIONAL'), ('ps', 'PSIQUICA'), ('so', 'SOCIAL'), ('te', 'TERAPIA '), ('oc', 'OCUPACIONAL')], default='fu', help_text='Tipo de parte', max_length=1)),
                ('valoracion_inicial', models.IntegerField(blank=True, default=django.utils.timezone.now, verbose_name='Valoracion inicial')),
                ('objetivos', models.TextField(help_text='Objetivos', max_length=1000)),
                ('informe', models.TextField(help_text='Informe', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_informe', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha del informe')),
                ('partes', models.ManyToManyField(help_text='Selecciona las partes del informe', related_name='partesDelInforme', to='appProgramaMainIndividualizado.ParteInforme')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
                ('parentesco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familiarResidente', to='appProgramaMainIndividualizado.Residente')),
            ],
        ),
    ]
