# Generated by Django 2.2.7 on 2019-11-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appProgramaMainIndividualizado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parteinforme',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sa', 'SANTIARIA'), ('fu', 'FUNCIONAL'), ('ps', 'PSIQUICA'), ('so', 'SOCIAL'), ('te', 'TERAPIA '), ('oc', 'OCUPACIONAL')], default='fu', help_text='Tipo de parte', max_length=2),
        ),
    ]
