# Generated by Django 2.2.7 on 2019-11-28 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('siglas', models.CharField(max_length=3, verbose_name='Siglas')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('fecha_nacimiento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de salida')),
                ('fecha_llegada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de llegada')),
                ('aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AeropuertoDeLlegada', to='appVuelos.Aeropuerto')),
                ('aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AeropuertoDeSalida', to='appVuelos.Aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de la reserva')),
                ('precio', models.IntegerField(default=80, verbose_name='Precio')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DatosDeCliente', to='appVuelos.Cliente')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VueloDeCliente', to='appVuelos.Vuelo')),
            ],
        ),
    ]
